/**
 * Truth or Dare — the game engine.
 *
 * Runs 100% client-side on every participant's device. Messages of
 * message_type 'game' carry a JSON payload with the event stream; each
 * device replays that stream to derive the same game state. There is no
 * server state and the payload is end-to-end encrypted like any other
 * message.
 *
 * Deterministic roulette: the round's current player is derived from
 * (seed, round, memberIds), so every device picks the same person without
 * anyone "holding the wheel".
 */

export type GameKind = 'truth-or-dare';

/** The single game message shape, serialised into the E2EE body. */
export type GameMessagePayload =
  | { kind: 'game'; game: 'truth-or-dare'; action: 'start'; seed: string; maxRounds: number }
  | { kind: 'game'; game: 'truth-or-dare'; action: 'choose'; playerId: string; choice: 'truth' | 'dare' }
  | { kind: 'game'; game: 'truth-or-dare'; action: 'challenge'; playerId: string; text: string }
  | { kind: 'game'; game: 'truth-or-dare'; action: 'done'; playerId: string }
  | { kind: 'game'; game: 'truth-or-dare'; action: 'end'; winnerId?: string };

export type TruthOrDareChoice = 'truth' | 'dare';

export interface TruthOrDareState {
  active: boolean;
  seed: string;
  maxRounds: number;
  round: number;
  /** Index into memberIds — the player whose turn it is. */
  currentIndex: number | null;
  currentPlayerId: string | null;
  choice: TruthOrDareChoice | null;
  /** Challenge text written by another member, pending resolution. */
  challenge: string | null;
  challengeBy: string | null;
  /** Players who completed their turn this round. */
  doneIds: string[];
  /** Rounds each player completed (for scoreboard). */
  scoreboard: Record<string, number>;
  ended: boolean;
  winnerId: string | null;
}

export const MAX_ROUNDS = 5;

/** Pure, stable hash — must match across devices. */
function hashString(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) {
    h ^= s.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

/**
 * Deterministic player pick for a round.
 * `memberIds` must be sorted so every device orders the same way.
 */
export function pickPlayer(seed: string, round: number, memberIds: string[]): number {
  if (memberIds.length === 0) return -1;
  const h = hashString(`${seed}:${round}`);
  return h % memberIds.length;
}

/** Initial state for a fresh game. */
export function emptyState(): TruthOrDareState {
  return {
    active: false,
    seed: '',
    maxRounds: MAX_ROUNDS,
    round: 1,
    currentIndex: null,
    currentPlayerId: null,
    choice: null,
    challenge: null,
    challengeBy: null,
    doneIds: [],
    scoreboard: {},
    ended: false,
    winnerId: null,
  };
}

/** Random seed, generated by the player who starts the game. */
export function newSeed(): string {
  return Array.from(crypto.getRandomValues(new Uint8Array(16)))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}

/**
 * Replay the game event stream (all messages of type 'game' in a chat,
 * oldest first) into the current state.
 *
 * @param payloads      parsed game payloads, chronological
 * @param memberIds     member ids, SORTED — drives deterministic picks
 */
export function replayGame(payloads: GameMessagePayload[], memberIds: string[]): TruthOrDareState {
  const state = emptyState();

  for (const p of payloads) {
    switch (p.action) {
      case 'start': {
        state.active = true;
        state.seed = p.seed;
        state.maxRounds = p.maxRounds;
        state.round = 1;
        state.doneIds = [];
        state.scoreboard = {};
        state.choice = null;
        state.challenge = null;
        state.challengeBy = null;
        state.ended = false;
        state.winnerId = null;
        const idx = pickPlayer(state.seed, 1, memberIds);
        state.currentIndex = idx;
        state.currentPlayerId = idx >= 0 ? memberIds[idx] : null;
        break;
      }
      case 'choose': {
        state.choice = p.choice;
        state.challenge = null;
        state.challengeBy = null;
        break;
      }
      case 'challenge': {
        state.challenge = p.text;
        state.challengeBy = p.playerId;
        break;
      }
      case 'done': {
        if (!state.doneIds.includes(p.playerId)) state.doneIds.push(p.playerId);
        state.scoreboard[p.playerId] = (state.scoreboard[p.playerId] ?? 0) + 1;
        // Next round unless everyone has gone or we hit maxRounds.
        const everyoneDone = state.doneIds.length >= memberIds.length;
        if (state.round >= state.maxRounds && everyoneDone) {
          state.ended = true;
          const sorted = Object.entries(state.scoreboard).sort((a, b) => b[1] - a[1]);
          state.winnerId = sorted.length > 0 ? sorted[0][0] : null;
          state.currentPlayerId = null;
          state.currentIndex = null;
        } else if (everyoneDone) {
          state.round += 1;
          state.doneIds = [];
          state.choice = null;
          state.challenge = null;
          state.challengeBy = null;
          const idx = pickPlayer(state.seed, state.round, memberIds);
          state.currentIndex = idx;
          state.currentPlayerId = idx >= 0 ? memberIds[idx] : null;
        }
        break;
      }
      case 'end': {
        state.ended = true;
        state.winnerId = p.winnerId ?? null;
        state.currentPlayerId = null;
        state.currentIndex = null;
        break;
      }
    }
  }

  return state;
}

/** Collect chronological game payloads from a list of raw messages. */
export function extractGamePayloads(
  messages: { attachment?: { kind: string } | null }[],
): GameMessagePayload[] {
  const out: GameMessagePayload[] = [];
  for (const m of messages) {
    const a = m.attachment;
    if (a && a.kind === 'game') {
      const p = a as unknown as GameMessagePayload;
      if (p.game === 'truth-or-dare' && p.action) out.push(p);
    }
  }
  return out;
}

/** Sorted member ids — the deterministic-order requirement for the wheel. */
export function sortedMemberIds(ids: string[]): string[] {
  return [...ids].sort();
}
